//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedycja.Model.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaActivity
    {
        public AreaActivity()
        {
            this.Drivers = new HashSet<Driver>();
        }
    
        public int id { get; set; }
        public string AreaName { get; set; }
    
        public virtual ICollection<Driver> Drivers { get; set; }
    }
}
