//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedycja.Model.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Comments = new HashSet<Comment>();
            this.StatusHistories = new HashSet<StatusHistory>();
        }
    
        public int id { get; set; }
        public Nullable<int> idLoad { get; set; }
        public Nullable<int> idWorker { get; set; }
        public Nullable<int> idStatus { get; set; }
        public Nullable<int> idTypeVehicles { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public Nullable<int> idDriver { get; set; }
        public Nullable<int> idRoutes { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Load Load { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual TypesVehicle TypesVehicle { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ICollection<StatusHistory> StatusHistories { get; set; }
        public virtual Route Route { get; set; }
    }
}
