//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedycja.Model.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string StartPoint { get; set; }
        public string EndPoint { get; set; }
        public Nullable<double> StartLat { get; set; }
        public Nullable<double> StartLong { get; set; }
        public Nullable<double> EndLat { get; set; }
        public Nullable<double> EndLong { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
