//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedycja.Model.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string StartCountry { get; set; }
        public string StartCity { get; set; }
        public string StartStreet { get; set; }
        public string EndCountry { get; set; }
        public string EndCity { get; set; }
        public string EndStreet { get; set; }
        public System.Data.Entity.Spatial.DbGeography StartCoord { get; set; }
        public System.Data.Entity.Spatial.DbGeography EndCoord { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
