//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spedycja.Model.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesFreight
    {
        public TypesFreight()
        {
            this.Loads = new HashSet<Load>();
        }
    
        public int id { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Load> Loads { get; set; }
    }
}
